# This workflow will deploy to the Flexion Azure environment via Bicep

name: Azure ARM

on:
  workflow_run:
    workflows: ["ESLint"]
#      - ', "React.js Build CI"'
    types:
      - completed
#    branches:
#      - '111-azure-iac'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: testing
        run: |
          echo github.event.workflow_run

        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          failOnStdErr: false